from datatime import datetime

from pymongo import MongoClient 
from pymong.errors import CollectionFailure

def main():
    try:
        c=MongClient('localhost',27017)

         

